version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 1234:5672
        - 1236:15672
    networks:
        - rabbitmq_go_net

    environment:
        - "RABBITMQ_DEFAULT_PASS=pass"
        - "RABBITMQ_DEFAULT_USER=user"
        - "RABBITMQ_DEFAULT_VHOST='vhost'"

networks:
  rabbitmq_go_net:
    driver: bridge